version: "3"
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8070:80
    volumes:
      - ./html:/var/www/html
      - ./apache-config:/etc/apache2/sites-enabled
    depends_on:
      - composer
    working_dir: /var/www/html
    command: ["apache2-foreground"]
  composer:
    image: composer:latest
    volumes:
      - ./html:/app
    working_dir: /app
    command: ["composer", "install"]
